In [1]:
import math
import numpy as np

In [2]:
#samples for class1
X1 = np.array([[5,3],[3,5],[3,4],[4,5],[4,7],[5,6]])
#samples for class2
X2 = np.array([[9,10],[7,7],[8,5],[8,8],[7,2],[10,8]])

In [3]:
u1 = X1.mean(axis = 0)
u2 = X2.mean(axis = 0)

In [38]:
def cals(X,u):
    return ((X-u).T.dot(X-u))/(len(X)-1)

In [39]:
S1 = cals(X1,u1)

In [41]:
S2 = cals(X2,u2)

In [42]:
S1,S2

(array([[0.8, 0. ],
        [0. , 2. ]]),
 array([[1.36666667, 2.06666667],
        [2.06666667, 7.86666667]]))

In [43]:
Sw = S1+S2

In [44]:
Sw

array([[2.16666667, 2.06666667],
       [2.06666667, 9.86666667]])

In [74]:
Sb = (u1-u2).reshape(2,1).dot((u1-u2).reshape(1,2))

In [75]:
Sb

array([[17.36111111,  6.94444444],
       [ 6.94444444,  2.77777778]])

In [78]:
np.linalg.inv(Sw).dot(Sb)

array([[ 9.1744609 ,  3.66978436],
       [-1.21784879, -0.48713952]])

In [79]:
np.linalg.eig(np.linalg.inv(Sw).dot(Sb))

(array([8.68732138e+00, 5.55111512e-17]),
 array([[ 0.99130435, -0.37139068],
        [-0.13158907,  0.92847669]]))